### ISSUE TITLE
Can't compile with electron-rebuild

### ISSUE THREAD

**Issue by HughIsaacs2** [holepunchto/sodium-native#144]
> fatal error C1083: Cannot open include file: 'sodium/version.h': No such file or directory

No matter what I do in the CLI, I get this error.

**Comment by joelfischerr** [comment]
Have you tried to run `npm run fetch-libsodium` as described in contributing.md?

**Comment by staltz** [comment]
The solution is to ignore sodium-native since its prebuilds are N-API and run easily on Electron already. In `electron-rebuild`, you can ignore `sodium-native` by listing all the other modules to be compiled in the options `onlyModules`: https://github.com/electron/electron-rebuild#how-can-i-integrate-this-into-grunt--gulp--whatever

E.g.:

```js
onlyModules: ['bufferutil', 'leveldown', 'utf-8-validate'],
// notice that `sodium-native` is not here
```
