### ISSUE TITLE
crypto_secretstream_xchacha20poly1305_state_new is missing since v3.0.0

### ISSUE THREAD

**Issue by letalumil** [holepunchto/sodium-native#180]
Hi there,

I'm currently busy migrating a project from sodium-native v2.4.6 to v4.0.1.
It turned out that the `crypto_secretstream_xchacha20poly1305_state_new` method [was removed](https://github.com/sodium-friends/sodium-native/commit/286576fdbad466f14fbdda9197c6d5738e25196b) during the N-API implementation.

However, the method is still described in the [docs](https://sodium-friends.github.io/docs/docs/streamencryption#crypto_secretstream_xchacha20poly1305_state_new).

As the project I am working on relies on this method, can I ask if the method was removed on purpose? Is there any way to get it back?

Thanks in advance!

**Comment by chm-diederichs** [comment]
Hi, thanks for your message, the docs are indeed out of date.

During the N-API migration we decided to use state buffers instead of opaque state instances, since it's closer aligned with the API of the underlying Libsodium [method](https://libsodium.gitbook.io/doc/secret-key_cryptography/secretstream).

You can use the `secretstream` API like so:
```js
const state = Buffer.alloc(sodium.crypto_secretstream_xchacha20poly1305_STATEBYTES)

sodium.crypto_secretstream_xchacha20poly1305_init_push(state, header, key)
sodium.crypto_secretstream_xchacha20poly1305_push(state, ciphertext, message, ad, tag)
// ... rest of code here
```

I'll update the docs now, but the rest of the `secretstream` methods are documented correctly.

Let me know if you have any further issues!

**Comment by chm-diederichs** [comment]
Note that the API is documented here: https://sodium-friends.github.io/docs/docs/streamencryption#stateful-api
