### ISSUE TITLE
n-api support

### ISSUE THREAD

**Issue by scriptjs** [holepunchto/sodium-native#68]
Are there any plans to make sodium native compatible with n-api?

**Comment by mafintosh** [comment]
Yes there is! It should not be hard as well as this is mostly macros

**Comment by emilbayes** [comment]
What's the status on Node 6 support for n-api?

**Comment by scriptjs** [comment]
@emilbayes Its really node 8.6.0 forward but I see no reason not to move ahead with a version while maintaining node 6 compatibility for legacy code with the previous version.

@mafintosh Yup. I am willing to get the ball rolling but might require some help along the way. Its a good way to get more comfortable with the new api with some benefits.

**Comment by scriptjs** [comment]
So I'll fork for the time being for a 3.0.0 and see how this goes.

**Comment by emilbayes** [comment]
@scriptjs Also have a quick look at the stuff going on in pull requests, specifically #55 is very important, but also #36, #62 and #67 will land with next major version 😃

The best places to start are probably with `crypto_generichash` and `crypto_secretstream`. `sodium_malloc` is also very important

**Comment by scriptjs** [comment]
@emilbayes Thanks, I'll keep an eye on what is happening. I wish to use sodium-native to get my feet with with n-api to get something tangible at the outset. From there, I think the rest will come. I'll reach out to you and @mafintosh once I have something to play with or have questions along the way.

**Comment by emilbayes** [comment]
@scriptjs Cool! `crypto_generichash_*` is pretty representative for most `sodium-native` functions, take an output buffer as the first argument and take some input buffers as the next. It also has a stateful version which is where you might want to look to #55, as that will change your approach. `crypto_secretstream_*` is tricky because it takes a bunch different types of pointers, some of which n-api may be better at representing. `sodium_malloc` is special in that it needs to wrap a chunk of memory in a buffer, but mustn't copy the memory, it needs to just wrap the pointer and a length.

**Comment by scriptjs** [comment]
First step was running the converter over the code after viewing [N-API - Next Generation Node API for Native Modules](https://www.youtube.com/watch?v=-Oniup60Afs). This led me to believe the native napi to be a c-only api and that node-addon-api was the route to wrap c++. I later encountered examples of c++ using the native napi which is what I was seeking.  So I'll begin modifying for native napi and running through the changes to classes and macros. Anyway, I've got a start. @mafintosh I am a bit puzzled why there is both a native approach and the node-addon-api that also uses napi as well. Can you enlighten me? Both appear to be maintained.

**Comment by mafintosh** [comment]
@scriptjs yea it's a bit confusing i agree. basically node-addon-api is the highly level api meant to be more "nan" like and n-api is the more low-level of the two. In general I just use the n-api one and then instead of doing classes and stuff like that I just expose struct pointers. Here is an example of that, https://github.com/mafintosh/turbo-net/blob/master/lib/connection.js#L22-L31

**Comment by emilbayes** [comment]
@scriptjs How did you do with this? :)

**Comment by scriptjs** [comment]
@emilbayes Got a bit sidetracked with a few things that got in the way. Its a priority so will be getting back to this later this week.

**Comment by emilbayes** [comment]
@scriptjs No worries, just wanted to follow up :)

**Comment by ThatOneBro** [comment]
Hey guys, my project is thinking about using this module but we would really love if it were using N-API bindings. What's the progress on this? Maybe some of our devs can lend a hand ;)

**Comment by scriptjs** [comment]
Sorry, I have completely fallen down on this. Too many things getting in the way. If anyone can get going on this sooner, please do. I will eventually get to it if not, but time has not been on my side.

**Comment by ThatOneBro** [comment]
Yeah no worries, it happens. I think someone from my team might end up working on this. We are definitely going to use this module in our project and so we might as well contribute if we can :)

**Comment by scriptjs** [comment]
@mafintosh has done some work to make this a bit easier. This could be helpful:

https://github.com/mafintosh/napi-macros.git
https://github.com/mafintosh/a-napi-example.git

**Comment by emilbayes** [comment]
Done now :)
