### ISSUE TITLE
request for a binding to crypto_box_beforenm

### ISSUE THREAD

**Issue by ameba23** [holepunchto/sodium-native#80]
We are putting together a module for sending messages with ephemeral keys over Secure Scuttlebutt.  We've had a strong recommendation to use sodium-native over other nodejs libsodium binding modules from several members of our community, and we would really like to.

We want to have something similar to `crypto_box_easy` but include extra information hashed into the shared secret (such as both public keys) to ensure it is only used for a specific perpose, mitigating the danger created when fragments of it end up in swap partition, etc.  

To do this we would like in best case to be able to call `crypto_box_beforenm` which currently isn't implemented in sodium-native. So we are requesting that it is (or to know why its a bad idea).

The discussion about this can be found on Scuttlebutt: %2qEtYbJ/tAiFuXHYgdfou7BvERxtIF7Cdq3NmjkSF4w=.sha256

Thanks!

**Comment by emilbayes** [comment]
I'm not sure I understand what the purpose is. I couldn't load the SSB thread for some reason. It's a bit of work to expose the various APIs with `*nm`, but maybe you'd be interested in sending a PR and I will review it? It should be pretty straightforward, but will take some work, copying from the other bindings that exist in `bindings.cc` :) It's a good learning experience never the less!

**Comment by keks** [comment]
>I'm not sure I understand what the purpose is.

To recap the discussion on SSB: The output of scalar multiplication returns a group element, which is indistinguishable from other group elements, but not from a random string. That's why `crypto_box_easy_beforenm` returns the HSalsa20 hash of the shared DH secret and `crypto_box_easy` uses that as the encryption key.

As far as I can see, sodium-native also doesn't expose HSalsa20, so there is no way to compute the key used by `crypto_box_easy` yourself. I don't think it would be a big problem to use a different hash function, such as blake2b, but it seems somehow "safer" to use the scheme that is already trusted by a lot of other users.

Small aside: I know that you can use HKDF to derive from group elements directly, but as far as I know this is only safe due to the extract-then-expand structure. sodium's KDF is BLAKE2b, which doesn't use that structure. BLAKE2x has an extract-then-expand structure, but that's not contained in sodium I think, and if it is, not in sodium-native.

> It's a bit of work to expose the various APIs with `*nm`, but maybe you'd be interested in sending a PR and I will review it?

I totally understand, but unfortunately I probably won't be able to help with that as I'm pretty busy currently.

**Comment by emilbayes** [comment]
I would just do like they do in the `kx` API, where they do a scalar multiplication but after that perform a `blake2b(p.n || pk1 || pk2)` to reduce the chances of some attacks: https://github.com/jedisct1/libsodium/issues/586#issuecomment-325182090

You could also mix more information into your shared secret using the same technique. From what I read you are not looking to create keys of 256-bits where this would be permissible, hence you do not need to expand to millions of bits. 

More information on using Blake2 for HMAC and HKDF: http://noiseprotocol.org/noise.html#hash-functions-and-hashing
Implementation: https://github.com/emilbayes/noise-protocol/blob/ad2f08fd09af1eb55433b9d34f71a85979cbbe9d/hash.js#L26-L52

HSalsa20 is not a general purpose hash function but specifically chosen so random nonces can be used with the Salsa20 stream cipher (yielding XSalsa20), so using it for your purpose I don't know the implications of. The nm apis are an optimisation for precomputing a key so you can use it for many calls to box.

@ameba23 Do you want to have a go at implementing this or should I close?

**Comment by keks** [comment]
Thanks @emilbayes for the pointer to the other issue, and explaining that HSalsa20 is a special-purpose hash-function.

@ameba23 
After learning that relying on HSalsa20 isn't a good idea anyways, I think I would go with
```
blake2b(key=blake2b(p.n), msg=(pk1 || pk2 || ctx))
```
because then the outer hash is a proper keyed hash, and the inner hash makes sure that the key for the keyed hash actually looks pseudorandom. `ctx` can then be further context, such as a string describing the purpose of the resulting key.

Note: `genericHash` is `blake2b`.

**Comment by ameba23** [comment]
@emilbayes @keks Thanks so much for taking the time to give this advice. This is all really useful.  I'm learning a lot, and really enjoying this!  

> Do you want to have a go at implementing this or should I close?

We can close the issue. I'd already started reading up on node-gyp and 'nan' as i've never used either, and was thinking to have a go at writing a binding.  But time is limited and unless we can identify a clear situation where its needed it, it probably doesn't make sense.
