### ISSUE TITLE
Feature request: Async crypto_box_seal and crypto_box_seal_open

### ISSUE THREAD

**Issue by felipeochoa** [holepunchto/sodium-native#86]
It would be great to have something like the pwhash async API to not hog the main thread.

**Comment by emilbayes** [comment]
Is this an issue you are experiencing? We should set up some benchmarks first. Do you want to attempt a PR? Happy to provide code review

**Comment by felipeochoa** [comment]
Sorry I think I made a mistake with the math, overestimating by a factor of 10x. Still think it could be worth pursuing a proper benchmark but here's what I was thinking through:

I haven't benchmarked, but Wikipedia says Salsa20 takes 4-14 cycles per byte. At 2Ghz, that would suggest a 10MB payload [my use case] takes ~~200-700ms~~ 20-70ms to process.

I unfortunately am not familiar with the Node C++ api/competent enough in C++ to make this happen myself.

20-70ms is still significant, but is also not the tree I need to bark up right now :) Feel free to close if you like

**Comment by emilbayes** [comment]
My concern is more the cost of context switching from Javascript to the libuv worker queue. If there's many back and forths the cost may be prohibitive, which is why I was asking for a benchmark and whether it was a real issue for you :)

I don't have time for this at the moment, and have no use for it myself, so I will leave the issue open and have tagged it appropriately. Maybe someone will come along, or if it becomes a real issue someone might be willing to pay for it being done.

For anyone else reading this later, I'm happy to provide guidance and code review for any PR

**Comment by jedisct1** [comment]
If you need to encrypt large messages, using `crypto_secretstream` might be a better option.
