### ISSUE TITLE
electron abi 70

### ISSUE THREAD

**Issue by MarijnFK** [holepunchto/sodium-native#99]
I get the following error when building electron-application:
Error: No native build was found for runtime=electron abi=70 platform=win32glibc arch=x64

**Comment by emilbayes** [comment]
Hi @MarijnFK,

It takes a major rewrite of the library to get it to ABI 70, so that's still an outstanding problem. See the issue about #95 for more info :) Latest supported so far is 67: https://github.com/lgeiger/node-abi/blob/79d73c3b676add0bd63899f021dabfa7e240be44/index.js#L58

Closing for now as this is in the works :)
